<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <LangVersion>latest</LangVersion>
    <RootNamespace>MiniLang</RootNamespace>
    <AssemblyName>MiniLang</AssemblyName>
    <NeutralLanguage>ru-RU</NeutralLanguage>
  </PropertyGroup>
</Project>
